using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CodeProjectSerialComms
{
    class Terminal2ECR
    {
        private string _ECRtoTerminal;
        private string length;
        private string _TransportHeader = "60";
        private string _TransportDestination = "0000";
        private string _TransportSource = "0000";
        private string _PresentationHeader = "1";
        private string _RequestIndicator = "1";
        private string _TransCode = "26";
        private string _ResponseCode = "00";
        private string _MoreIndicator = "0";
        
        private string _Responsetext = "APPROVAL      115800          ";
        private string _MerchantName = "MAYBANK                MYDEBIT                RECEIPT ";
        private string _TransactionDate = "170608";
        private string _TransactionTime = "115800";
        private string _ApprovalCode = "115800";
        private string _InvoiceNumber = "000006";
        private string _TerminalID = "16072832";
        private string _MerchantID = "000027009002510";
        private string _CardIssuerName = "VISA";
        private string _CardNo = "436501******9757";
        private string _ExpiryDate = "****";
        private string _BatchNumber = "000001";
        private string _ReferenceNo = "115800170608";
        private string _CardIssuerID = "41";
        private string _CardHolderName = "LIM LIH WEI";
        private string _ETX = "03";
        private string _LRC = "19";


         public void Terminal2ECR_Sale()
        {
           List<FieldTypeDefinition> fieldTypeDefinitions;
           Operations operations = new Operations();
         
           fieldTypeDefinitions = operations.addfieldTypeDefinitions();

            Console.WriteLine("================================  Data  ==============================================================");
            Console.WriteLine("DemoECRtoTerminal  : " + Operations.DemoTerminaltoECR);
            Console.WriteLine("DemoECRtoTerminal Length : " + Operations.DemoTerminaltoECR.Length);

            Console.WriteLine(Operations._STX);
            _ECRtoTerminal = Operations._STX;

            operations._Length = "35";
            operations._Length = operations.SaltString(operations._Length, Operations._salt);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _TransportHeader = operations.SaltString(_TransportHeader, Operations._salt);
            Console.WriteLine(_TransportHeader);
            _ECRtoTerminal += _TransportHeader;
            _TransportDestination = operations.SaltString(_TransportDestination, Operations._salt);
            Console.WriteLine(_TransportDestination);
            _ECRtoTerminal += _TransportDestination;
            _TransportSource = operations.SaltString(_TransportSource, Operations._salt);
            Console.WriteLine(_TransportSource);
            _ECRtoTerminal += _TransportSource;
            _PresentationHeader = operations.SaltString(_PresentationHeader, Operations._salt);
            Console.WriteLine(_PresentationHeader);
            _ECRtoTerminal += _PresentationHeader;
            _RequestIndicator = operations.SaltString(_RequestIndicator, Operations._salt);
            Console.WriteLine(_RequestIndicator);
            _ECRtoTerminal += _RequestIndicator;
            _TransCode = "20";
            _TransCode = operations.SaltString(_TransCode, Operations._salt);
            Console.WriteLine(_TransCode);
            _ECRtoTerminal += _TransCode;
            _ResponseCode = operations.SaltString(_ResponseCode, Operations._salt);
            Console.WriteLine(_ResponseCode);
            _ECRtoTerminal += _ResponseCode;
            _MoreIndicator = operations.SaltString(_MoreIndicator, Operations._salt);
            Console.WriteLine(_MoreIndicator);
            _ECRtoTerminal += _MoreIndicator;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "02";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _Responsetext = operations.PadStringRight(_Responsetext, Convert.ToInt16(operations._Length));
            _Responsetext = operations.HexString(_Responsetext);
            Console.WriteLine(_Responsetext);
            _ECRtoTerminal += _Responsetext;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D0";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _MerchantName = operations.PadStringRight(_MerchantName, Convert.ToInt16(operations._Length));
            _MerchantName = operations.HexString(_MerchantName);
            Console.WriteLine(_MerchantName);
            _ECRtoTerminal += _MerchantName;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "03";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _TransactionDate = operations.SaltString(_TransactionDate, Operations._salt);
            Console.WriteLine(_TransactionDate);
            _ECRtoTerminal += _TransactionDate;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "04";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _TransactionTime = operations.SaltString(_TransactionTime, Operations._salt);
            Console.WriteLine(_TransactionTime);
            _ECRtoTerminal += _TransactionTime;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "01";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _ApprovalCode = operations.SaltString(_ApprovalCode, Operations._salt);
            Console.WriteLine(_ApprovalCode);
            _ECRtoTerminal += _ApprovalCode;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "65";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _InvoiceNumber = operations.PadString(_InvoiceNumber, 6);
            _InvoiceNumber = operations.SaltString(_InvoiceNumber, Operations._salt);
            Console.WriteLine(_InvoiceNumber);
            _ECRtoTerminal += _InvoiceNumber;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "16";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _TerminalID = operations.SaltString(_TerminalID, Operations._salt);
            Console.WriteLine(_TerminalID);
            _ECRtoTerminal += _TerminalID;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D1";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _MerchantID = operations.SaltString(_MerchantID, Operations._salt);
            Console.WriteLine(_MerchantID);
            _ECRtoTerminal += _MerchantID;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D2";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _CardIssuerName = operations.PadStringRight(_CardIssuerName, Convert.ToInt16(operations._Length));
            _CardIssuerName = operations.HexString(_CardIssuerName);
            Console.WriteLine(_CardIssuerName);
            _ECRtoTerminal += _CardIssuerName;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "30";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _CardNo = operations.PadStringRight(_CardNo, Convert.ToInt16(operations._Length));
            _CardNo = operations.HexString(_CardNo);
            Console.WriteLine(_CardNo);
            _ECRtoTerminal += _CardNo;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "31";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _ExpiryDate = operations.PadStringRight(_ExpiryDate, Convert.ToInt16(operations._Length));
            _ExpiryDate = operations.HexString(_ExpiryDate);
            Console.WriteLine(_ExpiryDate);
            _ECRtoTerminal += _ExpiryDate;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "50";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _BatchNumber = operations.SaltString(_BatchNumber, Operations._salt);
            Console.WriteLine(_BatchNumber);
            _ECRtoTerminal += _BatchNumber;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D3";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _ReferenceNo = operations.SaltString(_ReferenceNo, Operations._salt);
            Console.WriteLine(_ReferenceNo);
            _ECRtoTerminal += _ReferenceNo;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D4";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _CardIssuerID = operations.SaltString(_CardIssuerID, Operations._salt);
            Console.WriteLine(_CardIssuerID);
            _ECRtoTerminal += _CardIssuerID;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            operations._FieldType = "D5";
            operations._Length = operations.getLengthfromFeildType(fieldTypeDefinitions, operations._FieldType);
            operations._FieldType = operations._FieldType.TrimStart(new char[] { 'D' });
            operations._FieldType = operations.SaltString(operations._FieldType, Operations._salt);
            operations._FieldType = "44" + operations._FieldType;
            Console.WriteLine(operations._FieldType);
            _ECRtoTerminal += operations._FieldType;
            operations._Length = operations.PadString(operations._Length, 4);
            Console.WriteLine(operations._Length);
            _ECRtoTerminal += operations._Length;
            _CardHolderName = operations.PadStringRight(_CardHolderName, Convert.ToInt16(operations._Length));
            _CardHolderName = operations.HexString(_CardHolderName);
            Console.WriteLine(_CardHolderName);
            _ECRtoTerminal += _CardHolderName;
            Console.WriteLine(Operations._Seperator);
            _ECRtoTerminal += Operations._Seperator;
            Console.WriteLine(_ETX);
            _ECRtoTerminal += _ETX;
            Console.WriteLine(_LRC);
            _ECRtoTerminal += _LRC;
            Console.WriteLine("");
            Console.WriteLine("_ECRtoTerminal  : " + _ECRtoTerminal);
            Console.WriteLine("_ECRtoTerminal Length : " + _ECRtoTerminal.Length);
            Console.ReadKey();
            Console.ReadKey();

        }



    }
}
